### ISSUE TITLE
Another sdf library

### ISSUE THREAD

**Issue by soypat** [Irev-Dev/curated-code-cad#23]
I've rewritten `sdfx` to be more user friendly, faster, decoupled and just all around more future-proof. https://github.com/soypat/sdf

**Comment by Irev-Dev** [comment]
I think I saw then forgot about this, feel free to ping me if I'm ignoring something.

I wasn't sure exactly how to add this to the list, so I just added a note under the original sdfx entry in https://github.com/Irev-Dev/curated-code-cad/commit/78b01745bc8c0d46085e997a8666e8350698091d.
