### ISSUE TITLE
Add manifold

### ISSUE THREAD

**Issue by pca006132** [Irev-Dev/curated-code-cad#25]
[Manifold](https://github.com/elalish/manifold) is a fast and robust mesh boolean library with JS (via WASM), C and Python bindings. It is integrated in OpenSCAD as experimental backend, and is significantly faster than CGAL.

Users can use https://manifoldcad.org/ web demo (single threaded for now). We provide CSG and SDF, with Clipper2 integration for 2D subsystem. There are also other features such as convex hull (provided by an external library), mesh smoothing, mesh warping (custom non-linear vertex transformation).

**Comment by Irev-Dev** [comment]
Care to make a PR following the same format as the rest?
