### ISSUE TITLE
Recommend Dynamo instead of/next to DynFreeCAD

### ISSUE THREAD

**Issue by infeeeee** [Irev-Dev/curated-code-cad#3]
DynFreeCAD is just a package for Dynamo. The node editor itself is Dynamo, DynFreeCAD just connects Dynamo and FreeCAD. So basically modeling takes place in Dynamo or in FreeCAD, DynFreeCAD just wraps the FreeCAD API into Dynamo nodes.

Dynamo itself is open source, licensed under Apache 2.0: https://github.com/DynamoDS/Dynamo

You already linked dynamo's forum. Dynamo's documentation is here: https://primer.dynamobim.org/

I think this should be on the list, DynFreeCAD can't do anything by itself.

**Comment by Irev-Dev** [comment]
Thanks @infeeeee, I'll fix that soon.

**Comment by Irev-Dev** [comment]
Sorry, Took me a while. That's been update.

**Comment by Irev-Dev** [comment]
@infeeeee If you wanted to give me a blurb about Dynamo that better fits the context of being in a list of other cad options. (how it differentiates etc), I'd be more than happy to include it. At the end of the day I don't know that much about each individual project in this list, as so it's hard to do them all justice.
